---
.gitignore:
  required:
    - '.git/'
    - '.*.sw[op]'
    - '.metadata'
    - '.yardoc'
    - '.yardwarns'
    - '*.iml'
    - '/.bundle/'
    - '/.idea/'
    - '/coverage/'
    - '/bin/'
    - '/doc/'
    - '/Gemfile.local'
    - '/junit/'
    - '/log/'
    - '/pkg/'
    - '/spec/fixtures/manifests/'
    - '/spec/fixtures/modules/'
    - '/tmp/'
    - '/vendor/'
    - '/convert_report.txt'
    - '/update_report.txt'
    - '.project'
    - '.envrc'
    - '/inventory.yaml'
    - '/.gem'
    - '/.bash_history'
    - '/.local'
    - '/examples/.byebug_history'
.gitlab-ci.yml:
  Quality checks:
    extends: .quality_check
  Module Build:
    extends:  .em_build
  Module Publish:
    extends:  .em_publish
  #
  # Acceptance tests
  #
  oci_core_instance Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_instance
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_instance.rb"
        - "lib/puppet/type/oci_core_instance/*.rb"
        - "lib/provider/oci_core_instance/*.rb"
        - "spec/acceptance/oci_core_instance_spec.rb"

  oci_identity_user Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_identity_user
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_identity_user.rb"
        - "lib/puppet/type/oci_identity_user/*.rb"
        - "lib/provider/oci_identity_user/*.rb"
        - "spec/acceptance/oci_identity_user_spec.rb"
  #
  # Because removing the compartments sometimes takes to long (no cause yet)
  # We disable this test for now.
  #
  # oci_identity_compartment Acceptance test:
  #   extends: .named_litmus_acceptance_test
  #   variables:
  #     type: oci_identity_compartment
  #     image: acc_base
  #   only:
  #     changes:
  #       - "lib/puppet/feature/*.rb"
  #       - "lib/puppet_x/**/*.rb"
  #       - "lib/puppet/type/oci_identity_compartment.rb"
  #       - "lib/puppet/type/oci_identity_compartment/*.rb"
  #       - "lib/provider/oci_identity_compartment/*.rb"
  #       - "spec/acceptance/oci_identity_compartment_spec.rb"
  oci_identity_group Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_identity_group
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_identity_group.rb"
        - "lib/puppet/type/oci_identity_group/*.rb"
        - "lib/provider/oci_identity_group/*.rb"
        - "spec/acceptance/oci_identity_group_spec.rb"

  oci_budget_budget Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_budget_budget
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_budget_budget.rb"
        - "lib/puppet/type/oci_budget_budget/*.rb"
        - "lib/provider/oci_budget_budget/*.rb"
        - "spec/acceptance/oci_budget_budget_spec.rb"

  oci_core_cpe Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_cpe
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_cpe.rb"
        - "lib/puppet/type/oci_core_cpe/*.rb"
        - "lib/provider/oci_core_cpe/*.rb"
        - "spec/acceptance/oci_core_cpe_spec.rb"
  oci_core_drg Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_drg
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_drg.rb"
        - "lib/puppet/type/oci_core_drg/*.rb"
        - "lib/provider/oci_core_drg/*.rb"
        - "spec/acceptance/oci_core_drg_spec.rb"
  oci_core_ip_sec_connection Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_ip_sec_connection
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_ip_sec_connection.rb"
        - "lib/puppet/type/oci_core_ip_sec_connection/*.rb"
        - "lib/provider/oci_core_ip_sec_connection/*.rb"
        - "spec/acceptance/oci_core_ip_sec_connection_spec.rb"
  oci_core_vcn Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_vcn
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_vcn.rb"
        - "lib/puppet/type/oci_core_vcn/*.rb"
        - "lib/provider/oci_core_vcn/*.rb"
        - "spec/acceptance/oci_core_vcn_spec.rb"

  oci_core_volume Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_volume
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_volume.rb"
        - "lib/puppet/type/oci_core_volume/*.rb"
        - "lib/provider/oci_core_volume/*.rb"
        - "spec/acceptance/oci_core_volume_spec.rb"

  oci_identity_dynamic_group Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_identity_dynamic_group
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_identity_dynamic_group.rb"
        - "lib/puppet/type/oci_identity_dynamic_group/*.rb"
        - "lib/provider/oci_identity_dynamic_group/*.rb"
        - "spec/acceptance/oci_identity_dynamic_group_spec.rb"

  oci_identity_policy Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_identity_policy
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_identity_policy.rb"
        - "lib/puppet/type/oci_identity_policy/*.rb"
        - "lib/provider/oci_identity_policy/*.rb"
        - "spec/acceptance/oci_identity_policy_spec.rb"

  oci_identity_tag_namespace Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_identity_tag_namespace
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_identity_tag_namespace.rb"
        - "lib/puppet/type/oci_identity_tag_namespace/*.rb"
        - "lib/provider/oci_identity_tag_namespace/*.rb"
        - "spec/acceptance/oci_identity_tag_namespace_spec.rb"

  oci_core_volume_group Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_volume_group
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_volume_group.rb"
        - "lib/puppet/type/oci_core_volume_group/*.rb"
        - "lib/provider/oci_core_volume_group/*.rb"
        - "spec/acceptance/oci_core_volume_group_spec.rb"

  oci_core_dhcp_options Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_dhcp_options
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_dhcp_options.rb"
        - "lib/puppet/type/oci_core_dhcp_options/*.rb"
        - "lib/provider/oci_core_dhcp_options/*.rb"
        - "spec/acceptance/oci_core_dhcp_options_spec.rb"

  oci_core_volume_backup Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_volume_backup
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_volume_backup.rb"
        - "lib/puppet/type/oci_core_volume_backup/*.rb"
        - "lib/provider/oci_core_volume_backup/*.rb"
        - "spec/acceptance/oci_core_volume_backup_spec.rb"

  oci_core_internet_gateway Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_internet_gateway
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_internet_gateway.rb"
        - "lib/puppet/type/oci_core_internet_gateway/*.rb"
        - "lib/provider/oci_core_internet_gateway/*.rb"
        - "spec/acceptance/oci_core_internet_gateway_spec.rb"

  oci_core_local_peering_gateway Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_local_peering_gateway
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_local_peering_gateway.rb"
        - "lib/puppet/type/oci_core_local_peering_gateway/*.rb"
        - "lib/provider/oci_core_local_peering_gateway/*.rb"
        - "spec/acceptance/oci_core_local_peering_gateway_spec.rb"

  oci_core_nat_gateway Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_nat_gateway
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_nat_gateway.rb"
        - "lib/puppet/type/oci_core_nat_gateway/*.rb"
        - "lib/provider/oci_core_nat_gateway/*.rb"
        - "spec/acceptance/oci_core_nat_gateway_spec.rb"

  oci_core_network_security_group Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_network_security_group
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_network_security_group.rb"
        - "lib/puppet/type/oci_core_network_security_group/*.rb"
        - "lib/provider/oci_core_network_security_group/*.rb"
        - "spec/acceptance/oci_core_network_security_group_spec.rb"

  oci_core_route_table Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_route_table
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_route_table.rb"
        - "lib/puppet/type/oci_core_route_table/*.rb"
        - "lib/provider/oci_core_route_table/*.rb"
        - "spec/acceptance/oci_core_route_table_spec.rb"

  oci_core_security_list Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_security_list
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_security_list.rb"
        - "lib/puppet/type/oci_core_security_list/*.rb"
        - "lib/provider/oci_core_security_list/*.rb"
        - "spec/acceptance/oci_core_security_list_spec.rb"

  oci_core_service_gateway Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_core_service_gateway
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_core_service_gateway.rb"
        - "lib/puppet/type/oci_core_service_gateway/*.rb"
        - "lib/provider/oci_core_service_gateway/*.rb"
        - "spec/acceptance/oci_core_service_gateway_spec.rb"
  oci_key_management_vault Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_key_management_vault
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_key_management_vault.rb"
        - "lib/puppet/type/oci_key_management_vault/*.rb"
        - "lib/provider/oci_key_management_vault/*.rb"
        - "spec/acceptance/oci_key_management_vault_spec.rb"

  oci_key_management_key Acceptance test:
    extends: .named_litmus_acceptance_test
    variables:
      type: oci_key_management_key
      image: acc_base
    only:
      changes:
        - "lib/puppet/feature/*.rb"
        - "lib/puppet_x/**/*.rb"
        - "lib/puppet/type/oci_key_management_key.rb"
        - "lib/puppet/type/oci_key_management_key/*.rb"
        - "lib/provider/oci_key_management_key/*.rb"
        - "spec/acceptance/oci_key_management_key_spec.rb"
.pdkignore:
  required:
  - '.git/'
  - '.*.sw[op]'
  - '.metadata'
  - '.yardoc'
  - '.yardwarns'
  - '*.iml'
  - '/.bundle/'
  - '/.idea/'
  - '/.vagrant/'
  - '/coverage/'
  - '/bin/'
  - '/doc/'
  - '/Gemfile.local'
  - '/Gemfile.lock'
  - '/junit/'
  - '/log/'
  - '/pkg/'
  - '/spec/fixtures/manifests/'
  - '/spec/fixtures/modules/'
  - '/tmp/'
  - '/vendor/'
  - '/convert_report.txt'
  - '/update_report.txt'
  - '.DS_Store'
  - '.project'
  - '.envrc'
  - '/inventory.yaml'
  - '/appveyor.yml'
  - '/.fixtures.yml'
  - '/Gemfile'
  - '/.gitattributes'
  - '/.gitignore'
  - '/.gitlab-ci.yml'
  - '/.pdkignore'
  - '/Rakefile'
  - '/rakelib/'
  - '/.rspec'
  - '/.rubocop.yml'
  - '/.travis.yml'
  - '/.yardopts'
  - '/spec/'
  - '/.vscode/'
  - '.DS_Store'
  - '.fasterer.yml'
  - '.overcommit.yml'
  - '.project'
  - '.puppet-lint.rc'
  - '.rspec'
  - '.rubocop.yml'
  - '.vagrant/'
  - '.vendor/'
  - 'bin/'
  - 'encrypt.list'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Jenkinsfile'
  - 'junit/'
  - 'lib_source/'
  - 'log/'
  - 'Rakefile'
  - 'spec/'
  - 'test_env.sh'
  - 'tests/'
  - 'tmp/'
  - 'TODO.md'
  - 'Vagrantfile'
  - '.gems/'
  - '.fixtures.yml'
  - '.gem'
  - '.git'
  - '.gitattributes'
  - '.gitignore'
  - '.pmtignore'
  - '.sync.yml'
  - 'develop.sh'
  - 'litmus.sh'
  - '.gitlab-ci.yml'
  - 'inventory.yaml'
  - '.byebug_history'
  - '.pki/'
  - 'app/'
  - 'documentation/'
  - 'generate/'
  - '.local/'
  - '.bash_history'
.pmtignore:
  required:
    - '.gems/'
    - '.fixtures.yml'
    - '.gem'
    - '.git'
    - '.gitattributes'
    - '.gitignore'
    - '.pmtignore'
    - '.sync.yml'
    - 'develop.sh'
    - 'litmus.sh'
    - '.gitlab-ci.yml'
    - 'inventory.yaml'
    - '.byebug_history'
    - '.pki/'
    - 'app/'
    - 'documentation/'
Rakefile:
  unmanaged: true

Gemfile:
  required:
    ':unit_test':
      - gem: rspec-expectations
        version: '3.8.4'
    'out_of_groups':
      - gem: oci
        condition: "Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.3.0')"
      - gem: activesupport
        version: '< 6.0.0'
        condition: "Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.3.0')"
      - gem: yard
        condition: "Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.3.0')"
      - gem: byebug
        condition: "Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.3.0')"
.rubocop.yml:
  unmanaged: true
.rspec:
  required:
    - --format documentation
.puppet-lint.rc:
  required:
    - -----fail-on-warnings
    - -----no-140chars-check
    - -----no-quoted_booleans
    - -----no-variable_is_lowercase
